name: Compile Java Backend
on: [push, pull_request]

jobs:
  compile-backend:
    runs-on: ubuntu-latest
    name: Compile Java with Maven
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile with Maven
        run: mvn -f app/pom.xml clean compile
